// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"nancalacc/internal/biz"
	"nancalacc/internal/conf"
	"nancalacc/internal/data"
	"nancalacc/internal/dingtalk"
	"nancalacc/internal/server"
	"nancalacc/internal/service"
	"nancalacc/internal/task"
	"nancalacc/internal/wps"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application with database factory.
func wireApp(confServer *conf.Server, confData *conf.Data, tracing *conf.Tracing, logger log.Logger) (*kratos.App, func(), error) {
	databaseFactory := data.NewDatabaseFactory(confData, logger)
	client, err := data.NewRedisClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewDataWithFactory(databaseFactory, client, logger)
	if err != nil {
		return nil, nil, err
	}
	accounterRepo := data.NewAccounterRepo(dataData, logger)
	dingtalkDingtalk := dingtalk.NewDingTalkRepo(logger)
	wpsWps := wps.NewWps(logger)
	cacheService := data.NewLocalCacheService(logger)
	accounterUsecase := biz.NewAccounterUsecase(accounterRepo, dingtalkDingtalk, wpsWps, cacheService, logger)
	oauth2Usecase := biz.NewOauth2Usecase(dingtalkDingtalk, logger)
	fullSyncUsecase := biz.NewFullSyncUsecase(accounterRepo, dingtalkDingtalk, wpsWps, cacheService, logger)
	accountService := service.NewAccountService(accounterUsecase, oauth2Usecase, fullSyncUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, accountService, logger)
	httpServer := server.NewHTTPServer(confServer, accountService, logger, tracing)
	cronService := task.NewCronServiceWithJobs(accounterUsecase, logger)
	incrementalSyncUsecase := biz.NewIncrementalSyncUsecase(accounterRepo, dingtalkDingtalk, wpsWps, logger)
	dingTalkEventService := service.NewDingTalkEventService(incrementalSyncUsecase, logger)
	app := newApp(logger, grpcServer, httpServer, cronService, dingTalkEventService)
	return app, func() {
		cleanup()
	}, nil
}
