// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"nancalacc/internal/auth"
	"nancalacc/internal/biz"
	"nancalacc/internal/conf"
	"nancalacc/internal/data"
	"nancalacc/internal/dingtalk"
	"nancalacc/internal/server"
	"nancalacc/internal/service"
	"nancalacc/internal/task"
	"nancalacc/internal/wps"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confService *conf.Service, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	syncDB, err := data.NewMysqlSyncDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	mainDB, err := data.NewMysqlDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewRedisClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(syncDB, mainDB, client, logger)
	if err != nil {
		return nil, nil, err
	}
	accounterRepo := data.NewAccounterRepo(confService, dataData, logger)
	service_Auth_Dingtalk := conf.ProvideDingtalkConfig(confService)
	authenticator := auth.NewAppCacheAuthenticator(auth.NewAppAuthenticator(confService))
	dingtalkAuth := auth.NewDingtalkCacheAuthenticator(auth.NewDingTalkAuthenticator(confService))
	dingtalkDingtalk := dingtalk.NewDingTalkRepo(service_Auth_Dingtalk, dingtalkAuth, logger)
	wpsSync := wps.NewWpsSync(confService, logger)
	wpsWps := wps.NewWps(confService, logger)
	service_Business := conf.ProvideBusinessConfig(confService)
	cacheService := data.NewLocalCacheService(logger)
	accounterUsecase := biz.NewAccounterUsecase(accounterRepo, dingtalkDingtalk, authenticator, wpsSync, wpsWps, service_Business, cacheService, logger)
	oauth2Usecase := biz.NewOauth2Usecase(dingtalkDingtalk, service_Business, logger)
	accountService := service.NewAccountService(accounterUsecase, oauth2Usecase, logger)
	grpcServer := server.NewGRPCServer(confServer, accountService, logger)
	httpServer := server.NewHTTPServer(confServer, accountService, logger)
	cronService := task.NewCronServiceWithJobs(accounterUsecase, logger)
	accounterIncreUsecase := biz.NewAccounterIncreUsecase(accounterRepo, dingtalkDingtalk, authenticator, wpsSync, wpsWps, service_Business, logger)
	dingTalkEventService := service.NewDingTalkEventService(confService, logger, accounterIncreUsecase)
	app := newApp(logger, grpcServer, httpServer, cronService, dingTalkEventService)
	return app, func() {
		cleanup()
	}, nil
}
