// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	App           *App                   `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	Otel          *OpenTelemetry         `protobuf:"bytes,5,opt,name=otel,proto3" json:"otel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetOtel() *OpenTelemetry {
	if x != nil {
		return x.Otel
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	DatabaseSync  *Data_DatabaseSync     `protobuf:"bytes,2,opt,name=database_sync,json=databaseSync,proto3" json:"database_sync,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,3,opt,name=redis,proto3" json:"redis,omitempty"`
	Etcd          *Data_Etcd             `protobuf:"bytes,4,opt,name=etcd,proto3" json:"etcd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetDatabaseSync() *Data_DatabaseSync {
	if x != nil {
		return x.DatabaseSync
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetEtcd() *Data_Etcd {
	if x != nil {
		return x.Etcd
	}
	return nil
}

type App struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Env            string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	AppPackage     string                 `protobuf:"bytes,5,opt,name=app_package,json=appPackage,proto3" json:"app_package,omitempty"`
	AppId          string                 `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret      string                 `protobuf:"bytes,7,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	ThirdCompanyId string                 `protobuf:"bytes,8,opt,name=third_company_id,json=thirdCompanyId,proto3" json:"third_company_id,omitempty"`
	PlatformIds    string                 `protobuf:"bytes,9,opt,name=platform_ids,json=platformIds,proto3" json:"platform_ids,omitempty"`
	CompanyId      string                 `protobuf:"bytes,10,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	AccessKey      string                 `protobuf:"bytes,11,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey      string                 `protobuf:"bytes,12,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// 批量处理配置
	BatchSize     int32  `protobuf:"varint,13,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`    // 批量大小，默认500
	MaxWorkers    int32  `protobuf:"varint,14,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"` // 最大并发工作数，默认3
	LogLevel      string `protobuf:"bytes,15,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`        // 日志级别
	Logout        string `protobuf:"bytes,16,opt,name=logout,proto3" json:"logout,omitempty"`                            // 日志输出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *App) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *App) GetAppPackage() string {
	if x != nil {
		return x.AppPackage
	}
	return ""
}

func (x *App) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *App) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *App) GetThirdCompanyId() string {
	if x != nil {
		return x.ThirdCompanyId
	}
	return ""
}

func (x *App) GetPlatformIds() string {
	if x != nil {
		return x.PlatformIds
	}
	return ""
}

func (x *App) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *App) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *App) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *App) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *App) GetMaxWorkers() int32 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

func (x *App) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *App) GetLogout() string {
	if x != nil {
		return x.Logout
	}
	return ""
}

// OpenTelemetry 统一配置
type OpenTelemetry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ServiceName    string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion string                 `protobuf:"bytes,3,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	Environment    string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	// 追踪配置
	Traces *TracesConfig `protobuf:"bytes,5,opt,name=traces,proto3" json:"traces,omitempty"`
	// 指标配置
	Metrics *MetricsConfig `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// 日志配置
	Logs          *LogsConfig `protobuf:"bytes,7,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTelemetry) Reset() {
	*x = OpenTelemetry{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTelemetry) ProtoMessage() {}

func (x *OpenTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTelemetry.ProtoReflect.Descriptor instead.
func (*OpenTelemetry) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *OpenTelemetry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OpenTelemetry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *OpenTelemetry) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *OpenTelemetry) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *OpenTelemetry) GetTraces() *TracesConfig {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *OpenTelemetry) GetMetrics() *MetricsConfig {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *OpenTelemetry) GetLogs() *LogsConfig {
	if x != nil {
		return x.Logs
	}
	return nil
}

// 日志配置
type LogsConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Level          string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Format         string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Output         string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	FilePath       string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	MaxSize        int32                  `protobuf:"varint,6,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxBackups     int32                  `protobuf:"varint,7,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxAge         int32                  `protobuf:"varint,8,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Compress       bool                   `protobuf:"varint,9,opt,name=compress,proto3" json:"compress,omitempty"`
	Caller         bool                   `protobuf:"varint,10,opt,name=caller,proto3" json:"caller,omitempty"`
	Stacktrace     bool                   `protobuf:"varint,11,opt,name=stacktrace,proto3" json:"stacktrace,omitempty"`
	EscapeNewlines bool                   `protobuf:"varint,12,opt,name=escape_newlines,json=escapeNewlines,proto3" json:"escape_newlines,omitempty"`
	Gorm           *GormLog               `protobuf:"bytes,13,opt,name=gorm,proto3" json:"gorm,omitempty"`
	Loki           *LokiConfig            `protobuf:"bytes,14,opt,name=loki,proto3" json:"loki,omitempty"`
	// Zap配置
	UseZap               bool   `protobuf:"varint,15,opt,name=use_zap,json=useZap,proto3" json:"use_zap,omitempty"`                                             // 是否使用zap logger
	ZapDevelopment       bool   `protobuf:"varint,16,opt,name=zap_development,json=zapDevelopment,proto3" json:"zap_development,omitempty"`                     // 是否为开发模式
	ZapDisableCaller     bool   `protobuf:"varint,17,opt,name=zap_disable_caller,json=zapDisableCaller,proto3" json:"zap_disable_caller,omitempty"`             // 是否禁用调用者信息
	ZapDisableStacktrace bool   `protobuf:"varint,18,opt,name=zap_disable_stacktrace,json=zapDisableStacktrace,proto3" json:"zap_disable_stacktrace,omitempty"` // 是否禁用堆栈跟踪
	ZapEncoding          string `protobuf:"bytes,19,opt,name=zap_encoding,json=zapEncoding,proto3" json:"zap_encoding,omitempty"`                               // 编码格式: json, console
	ZapTimeKey           string `protobuf:"bytes,20,opt,name=zap_time_key,json=zapTimeKey,proto3" json:"zap_time_key,omitempty"`                                // 时间字段名
	ZapLevelKey          string `protobuf:"bytes,21,opt,name=zap_level_key,json=zapLevelKey,proto3" json:"zap_level_key,omitempty"`                             // 级别字段名
	ZapNameKey           string `protobuf:"bytes,22,opt,name=zap_name_key,json=zapNameKey,proto3" json:"zap_name_key,omitempty"`                                // 名称字段名
	ZapCallerKey         string `protobuf:"bytes,23,opt,name=zap_caller_key,json=zapCallerKey,proto3" json:"zap_caller_key,omitempty"`                          // 调用者字段名
	ZapFunctionKey       string `protobuf:"bytes,24,opt,name=zap_function_key,json=zapFunctionKey,proto3" json:"zap_function_key,omitempty"`                    // 函数字段名
	ZapMessageKey        string `protobuf:"bytes,25,opt,name=zap_message_key,json=zapMessageKey,proto3" json:"zap_message_key,omitempty"`                       // 消息字段名
	ZapStacktraceKey     string `protobuf:"bytes,26,opt,name=zap_stacktrace_key,json=zapStacktraceKey,proto3" json:"zap_stacktrace_key,omitempty"`              // 堆栈跟踪字段名
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LogsConfig) Reset() {
	*x = LogsConfig{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsConfig) ProtoMessage() {}

func (x *LogsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsConfig.ProtoReflect.Descriptor instead.
func (*LogsConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *LogsConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *LogsConfig) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogsConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *LogsConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *LogsConfig) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LogsConfig) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *LogsConfig) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *LogsConfig) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *LogsConfig) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *LogsConfig) GetCaller() bool {
	if x != nil {
		return x.Caller
	}
	return false
}

func (x *LogsConfig) GetStacktrace() bool {
	if x != nil {
		return x.Stacktrace
	}
	return false
}

func (x *LogsConfig) GetEscapeNewlines() bool {
	if x != nil {
		return x.EscapeNewlines
	}
	return false
}

func (x *LogsConfig) GetGorm() *GormLog {
	if x != nil {
		return x.Gorm
	}
	return nil
}

func (x *LogsConfig) GetLoki() *LokiConfig {
	if x != nil {
		return x.Loki
	}
	return nil
}

func (x *LogsConfig) GetUseZap() bool {
	if x != nil {
		return x.UseZap
	}
	return false
}

func (x *LogsConfig) GetZapDevelopment() bool {
	if x != nil {
		return x.ZapDevelopment
	}
	return false
}

func (x *LogsConfig) GetZapDisableCaller() bool {
	if x != nil {
		return x.ZapDisableCaller
	}
	return false
}

func (x *LogsConfig) GetZapDisableStacktrace() bool {
	if x != nil {
		return x.ZapDisableStacktrace
	}
	return false
}

func (x *LogsConfig) GetZapEncoding() string {
	if x != nil {
		return x.ZapEncoding
	}
	return ""
}

func (x *LogsConfig) GetZapTimeKey() string {
	if x != nil {
		return x.ZapTimeKey
	}
	return ""
}

func (x *LogsConfig) GetZapLevelKey() string {
	if x != nil {
		return x.ZapLevelKey
	}
	return ""
}

func (x *LogsConfig) GetZapNameKey() string {
	if x != nil {
		return x.ZapNameKey
	}
	return ""
}

func (x *LogsConfig) GetZapCallerKey() string {
	if x != nil {
		return x.ZapCallerKey
	}
	return ""
}

func (x *LogsConfig) GetZapFunctionKey() string {
	if x != nil {
		return x.ZapFunctionKey
	}
	return ""
}

func (x *LogsConfig) GetZapMessageKey() string {
	if x != nil {
		return x.ZapMessageKey
	}
	return ""
}

func (x *LogsConfig) GetZapStacktraceKey() string {
	if x != nil {
		return x.ZapStacktraceKey
	}
	return ""
}

// Loki配置
type LokiConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LokiConfig) Reset() {
	*x = LokiConfig{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LokiConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LokiConfig) ProtoMessage() {}

func (x *LokiConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LokiConfig.ProtoReflect.Descriptor instead.
func (*LokiConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *LokiConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *LokiConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// GORM日志配置
type GormLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlowThreshold string                 `protobuf:"bytes,1,opt,name=slow_threshold,json=slowThreshold,proto3" json:"slow_threshold,omitempty"`
	LogLevel      string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GormLog) Reset() {
	*x = GormLog{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GormLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GormLog) ProtoMessage() {}

func (x *GormLog) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GormLog.ProtoReflect.Descriptor instead.
func (*GormLog) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *GormLog) GetSlowThreshold() string {
	if x != nil {
		return x.SlowThreshold
	}
	return ""
}

func (x *GormLog) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

// 追踪配置
type TracesConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	VerboseLogging  bool                   `protobuf:"varint,2,opt,name=verbose_logging,json=verboseLogging,proto3" json:"verbose_logging,omitempty"`
	LogRequestSize  bool                   `protobuf:"varint,3,opt,name=log_request_size,json=logRequestSize,proto3" json:"log_request_size,omitempty"`
	LogResponseSize bool                   `protobuf:"varint,4,opt,name=log_response_size,json=logResponseSize,proto3" json:"log_response_size,omitempty"`
	LogHeaders      bool                   `protobuf:"varint,5,opt,name=log_headers,json=logHeaders,proto3" json:"log_headers,omitempty"`
	LogQueryParams  bool                   `protobuf:"varint,6,opt,name=log_query_params,json=logQueryParams,proto3" json:"log_query_params,omitempty"`
	Jaeger          *JaegerConfig          `protobuf:"bytes,7,opt,name=jaeger,proto3" json:"jaeger,omitempty"`
	Otlp            *OtlpConfig            `protobuf:"bytes,8,opt,name=otlp,proto3" json:"otlp,omitempty"`
	Prometheus      *PrometheusConfig      `protobuf:"bytes,9,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TracesConfig) Reset() {
	*x = TracesConfig{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracesConfig) ProtoMessage() {}

func (x *TracesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracesConfig.ProtoReflect.Descriptor instead.
func (*TracesConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *TracesConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TracesConfig) GetVerboseLogging() bool {
	if x != nil {
		return x.VerboseLogging
	}
	return false
}

func (x *TracesConfig) GetLogRequestSize() bool {
	if x != nil {
		return x.LogRequestSize
	}
	return false
}

func (x *TracesConfig) GetLogResponseSize() bool {
	if x != nil {
		return x.LogResponseSize
	}
	return false
}

func (x *TracesConfig) GetLogHeaders() bool {
	if x != nil {
		return x.LogHeaders
	}
	return false
}

func (x *TracesConfig) GetLogQueryParams() bool {
	if x != nil {
		return x.LogQueryParams
	}
	return false
}

func (x *TracesConfig) GetJaeger() *JaegerConfig {
	if x != nil {
		return x.Jaeger
	}
	return nil
}

func (x *TracesConfig) GetOtlp() *OtlpConfig {
	if x != nil {
		return x.Otlp
	}
	return nil
}

func (x *TracesConfig) GetPrometheus() *PrometheusConfig {
	if x != nil {
		return x.Prometheus
	}
	return nil
}

// 指标配置
type MetricsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Prometheus    *PrometheusConfig      `protobuf:"bytes,2,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsConfig) Reset() {
	*x = MetricsConfig{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsConfig) ProtoMessage() {}

func (x *MetricsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsConfig.ProtoReflect.Descriptor instead.
func (*MetricsConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *MetricsConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MetricsConfig) GetPrometheus() *PrometheusConfig {
	if x != nil {
		return x.Prometheus
	}
	return nil
}

// Jaeger配置
type JaegerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JaegerConfig) Reset() {
	*x = JaegerConfig{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JaegerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JaegerConfig) ProtoMessage() {}

func (x *JaegerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JaegerConfig.ProtoReflect.Descriptor instead.
func (*JaegerConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{10}
}

func (x *JaegerConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *JaegerConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// OTLP配置
type OtlpConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtlpConfig) Reset() {
	*x = OtlpConfig{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtlpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtlpConfig) ProtoMessage() {}

func (x *OtlpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtlpConfig.ProtoReflect.Descriptor instead.
func (*OtlpConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{11}
}

func (x *OtlpConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OtlpConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OtlpConfig) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// Prometheus配置
type PrometheusConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Interval      string                 `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrometheusConfig) Reset() {
	*x = PrometheusConfig{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrometheusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrometheusConfig) ProtoMessage() {}

func (x *PrometheusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrometheusConfig.ProtoReflect.Descriptor instead.
func (*PrometheusConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{12}
}

func (x *PrometheusConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PrometheusConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PrometheusConfig) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wpsapp        *Auth_Wpsapp           `protobuf:"bytes,1,opt,name=wpsapp,proto3" json:"wpsapp,omitempty"`
	Dingtalk      *Auth_Dingtalk         `protobuf:"bytes,2,opt,name=dingtalk,proto3" json:"dingtalk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{13}
}

func (x *Auth) GetWpsapp() *Auth_Wpsapp {
	if x != nil {
		return x.Wpsapp
	}
	return nil
}

func (x *Auth) GetDingtalk() *Auth_Dingtalk {
	if x != nil {
		return x.Dingtalk
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Driver          string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,3,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	MaxIdleConns    int32                  `protobuf:"varint,4,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	ConnMaxLifetime string                 `protobuf:"bytes,5,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	Tag             string                 `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	SourceKey       string                 `protobuf:"bytes,7,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	Env             string                 `protobuf:"bytes,8,opt,name=env,proto3" json:"env,omitempty"`
	Enable          bool                   `protobuf:"varint,9,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Database) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_Database) GetConnMaxLifetime() string {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return ""
}

func (x *Data_Database) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Data_Database) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *Data_Database) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Data_Database) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type Data_DatabaseSync struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Driver          string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,3,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	MaxIdleConns    int32                  `protobuf:"varint,4,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	ConnMaxLifetime string                 `protobuf:"bytes,5,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	Tag             string                 `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	SourceKey       string                 `protobuf:"bytes,7,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	Env             string                 `protobuf:"bytes,8,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_DatabaseSync) Reset() {
	*x = Data_DatabaseSync{}
	mi := &file_conf_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_DatabaseSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_DatabaseSync) ProtoMessage() {}

func (x *Data_DatabaseSync) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_DatabaseSync.ProtoReflect.Descriptor instead.
func (*Data_DatabaseSync) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_DatabaseSync) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_DatabaseSync) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_DatabaseSync) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_DatabaseSync) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_DatabaseSync) GetConnMaxLifetime() string {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return ""
}

func (x *Data_DatabaseSync) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Data_DatabaseSync) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *Data_DatabaseSync) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,4,opt,name=db,proto3" json:"db,omitempty"`
	Enable        bool                   `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,6,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,7,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Redis) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

type Data_Etcd struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Endpoints         []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	DialTimeout       string                 `protobuf:"bytes,2,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	ConfigPrefix      string                 `protobuf:"bytes,3,opt,name=config_prefix,json=configPrefix,proto3" json:"config_prefix,omitempty"`
	EnableConfigWatch bool                   `protobuf:"varint,4,opt,name=enable_config_watch,json=enableConfigWatch,proto3" json:"enable_config_watch,omitempty"`
	Enable            bool                   `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Data_Etcd) Reset() {
	*x = Data_Etcd{}
	mi := &file_conf_conf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Etcd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Etcd) ProtoMessage() {}

func (x *Data_Etcd) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Etcd.ProtoReflect.Descriptor instead.
func (*Data_Etcd) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Data_Etcd) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Data_Etcd) GetDialTimeout() string {
	if x != nil {
		return x.DialTimeout
	}
	return ""
}

func (x *Data_Etcd) GetConfigPrefix() string {
	if x != nil {
		return x.ConfigPrefix
	}
	return ""
}

func (x *Data_Etcd) GetEnableConfigWatch() bool {
	if x != nil {
		return x.EnableConfigWatch
	}
	return false
}

func (x *Data_Etcd) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type Auth_Wpsapp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	AuthUrl       string                 `protobuf:"bytes,3,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	AuthPath      string                 `protobuf:"bytes,4,opt,name=auth_path,json=authPath,proto3" json:"auth_path,omitempty"`
	GrantType     string                 `protobuf:"bytes,5,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth_Wpsapp) Reset() {
	*x = Auth_Wpsapp{}
	mi := &file_conf_conf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth_Wpsapp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_Wpsapp) ProtoMessage() {}

func (x *Auth_Wpsapp) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_Wpsapp.ProtoReflect.Descriptor instead.
func (*Auth_Wpsapp) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{13, 0}
}

func (x *Auth_Wpsapp) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Auth_Wpsapp) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *Auth_Wpsapp) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *Auth_Wpsapp) GetAuthPath() string {
	if x != nil {
		return x.AuthPath
	}
	return ""
}

func (x *Auth_Wpsapp) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

type Auth_Dingtalk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AppKey        string                 `protobuf:"bytes,2,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	AppSecret     string                 `protobuf:"bytes,3,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	Timeout       string                 `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxConcurrent int64                  `protobuf:"varint,5,opt,name=maxConcurrent,proto3" json:"maxConcurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth_Dingtalk) Reset() {
	*x = Auth_Dingtalk{}
	mi := &file_conf_conf_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth_Dingtalk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_Dingtalk) ProtoMessage() {}

func (x *Auth_Dingtalk) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_Dingtalk.ProtoReflect.Descriptor instead.
func (*Auth_Dingtalk) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{13, 1}
}

func (x *Auth_Dingtalk) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Auth_Dingtalk) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *Auth_Dingtalk) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *Auth_Dingtalk) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Auth_Dingtalk) GetMaxConcurrent() int64 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xd5\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12!\n" +
	"\x03app\x18\x03 \x01(\v2\x0f.kratos.api.AppR\x03app\x12$\n" +
	"\x04auth\x18\x04 \x01(\v2\x10.kratos.api.AuthR\x04auth\x12-\n" +
	"\x04otel\x18\x05 \x01(\v2\x19.kratos.api.OpenTelemetryR\x04otel\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x97\t\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12B\n" +
	"\rdatabase_sync\x18\x02 \x01(\v2\x1d.kratos.api.Data.DatabaseSyncR\fdatabaseSync\x12,\n" +
	"\x05redis\x18\x03 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12)\n" +
	"\x04etcd\x18\x04 \x01(\v2\x15.kratos.api.Data.EtcdR\x04etcd\x1a\x8d\x02\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12$\n" +
	"\x0emax_open_conns\x18\x03 \x01(\x05R\fmaxOpenConns\x12$\n" +
	"\x0emax_idle_conns\x18\x04 \x01(\x05R\fmaxIdleConns\x12*\n" +
	"\x11conn_max_lifetime\x18\x05 \x01(\tR\x0fconnMaxLifetime\x12\x10\n" +
	"\x03tag\x18\x06 \x01(\tR\x03tag\x12\x1d\n" +
	"\n" +
	"source_key\x18\a \x01(\tR\tsourceKey\x12\x10\n" +
	"\x03env\x18\b \x01(\tR\x03env\x12\x16\n" +
	"\x06enable\x18\t \x01(\bR\x06enable\x1a\xf9\x01\n" +
	"\fDatabaseSync\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12$\n" +
	"\x0emax_open_conns\x18\x03 \x01(\x05R\fmaxOpenConns\x12$\n" +
	"\x0emax_idle_conns\x18\x04 \x01(\x05R\fmaxIdleConns\x12*\n" +
	"\x11conn_max_lifetime\x18\x05 \x01(\tR\x0fconnMaxLifetime\x12\x10\n" +
	"\x03tag\x18\x06 \x01(\tR\x03tag\x12\x1d\n" +
	"\n" +
	"source_key\x18\a \x01(\tR\tsourceKey\x12\x10\n" +
	"\x03env\x18\b \x01(\tR\x03env\x1a\xf7\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x04 \x01(\x05R\x02db\x12\x16\n" +
	"\x06enable\x18\x05 \x01(\bR\x06enable\x12<\n" +
	"\fread_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x1a\xb4\x01\n" +
	"\x04Etcd\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x12!\n" +
	"\fdial_timeout\x18\x02 \x01(\tR\vdialTimeout\x12#\n" +
	"\rconfig_prefix\x18\x03 \x01(\tR\fconfigPrefix\x12.\n" +
	"\x13enable_config_watch\x18\x04 \x01(\bR\x11enableConfigWatch\x12\x16\n" +
	"\x06enable\x18\x05 \x01(\bR\x06enable\"\xcb\x03\n" +
	"\x03App\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\x12\x1f\n" +
	"\vapp_package\x18\x05 \x01(\tR\n" +
	"appPackage\x12\x15\n" +
	"\x06app_id\x18\x06 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\a \x01(\tR\tappSecret\x12(\n" +
	"\x10third_company_id\x18\b \x01(\tR\x0ethirdCompanyId\x12!\n" +
	"\fplatform_ids\x18\t \x01(\tR\vplatformIds\x12\x1d\n" +
	"\n" +
	"company_id\x18\n" +
	" \x01(\tR\tcompanyId\x12\x1d\n" +
	"\n" +
	"access_key\x18\v \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\f \x01(\tR\tsecretKey\x12\x1d\n" +
	"\n" +
	"batch_size\x18\r \x01(\x05R\tbatchSize\x12\x1f\n" +
	"\vmax_workers\x18\x0e \x01(\x05R\n" +
	"maxWorkers\x12\x1b\n" +
	"\tlog_level\x18\x0f \x01(\tR\blogLevel\x12\x16\n" +
	"\x06logout\x18\x10 \x01(\tR\x06logout\"\xaa\x02\n" +
	"\rOpenTelemetry\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x03 \x01(\tR\x0eserviceVersion\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x120\n" +
	"\x06traces\x18\x05 \x01(\v2\x18.kratos.api.TracesConfigR\x06traces\x123\n" +
	"\ametrics\x18\x06 \x01(\v2\x19.kratos.api.MetricsConfigR\ametrics\x12*\n" +
	"\x04logs\x18\a \x01(\v2\x16.kratos.api.LogsConfigR\x04logs\"\x87\a\n" +
	"\n" +
	"LogsConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x19\n" +
	"\bmax_size\x18\x06 \x01(\x05R\amaxSize\x12\x1f\n" +
	"\vmax_backups\x18\a \x01(\x05R\n" +
	"maxBackups\x12\x17\n" +
	"\amax_age\x18\b \x01(\x05R\x06maxAge\x12\x1a\n" +
	"\bcompress\x18\t \x01(\bR\bcompress\x12\x16\n" +
	"\x06caller\x18\n" +
	" \x01(\bR\x06caller\x12\x1e\n" +
	"\n" +
	"stacktrace\x18\v \x01(\bR\n" +
	"stacktrace\x12'\n" +
	"\x0fescape_newlines\x18\f \x01(\bR\x0eescapeNewlines\x12'\n" +
	"\x04gorm\x18\r \x01(\v2\x13.kratos.api.GormLogR\x04gorm\x12*\n" +
	"\x04loki\x18\x0e \x01(\v2\x16.kratos.api.LokiConfigR\x04loki\x12\x17\n" +
	"\ause_zap\x18\x0f \x01(\bR\x06useZap\x12'\n" +
	"\x0fzap_development\x18\x10 \x01(\bR\x0ezapDevelopment\x12,\n" +
	"\x12zap_disable_caller\x18\x11 \x01(\bR\x10zapDisableCaller\x124\n" +
	"\x16zap_disable_stacktrace\x18\x12 \x01(\bR\x14zapDisableStacktrace\x12!\n" +
	"\fzap_encoding\x18\x13 \x01(\tR\vzapEncoding\x12 \n" +
	"\fzap_time_key\x18\x14 \x01(\tR\n" +
	"zapTimeKey\x12\"\n" +
	"\rzap_level_key\x18\x15 \x01(\tR\vzapLevelKey\x12 \n" +
	"\fzap_name_key\x18\x16 \x01(\tR\n" +
	"zapNameKey\x12$\n" +
	"\x0ezap_caller_key\x18\x17 \x01(\tR\fzapCallerKey\x12(\n" +
	"\x10zap_function_key\x18\x18 \x01(\tR\x0ezapFunctionKey\x12&\n" +
	"\x0fzap_message_key\x18\x19 \x01(\tR\rzapMessageKey\x12,\n" +
	"\x12zap_stacktrace_key\x18\x1a \x01(\tR\x10zapStacktraceKey\"B\n" +
	"\n" +
	"LokiConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"M\n" +
	"\aGormLog\x12%\n" +
	"\x0eslow_threshold\x18\x01 \x01(\tR\rslowThreshold\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\"\x8e\x03\n" +
	"\fTracesConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12'\n" +
	"\x0fverbose_logging\x18\x02 \x01(\bR\x0everboseLogging\x12(\n" +
	"\x10log_request_size\x18\x03 \x01(\bR\x0elogRequestSize\x12*\n" +
	"\x11log_response_size\x18\x04 \x01(\bR\x0flogResponseSize\x12\x1f\n" +
	"\vlog_headers\x18\x05 \x01(\bR\n" +
	"logHeaders\x12(\n" +
	"\x10log_query_params\x18\x06 \x01(\bR\x0elogQueryParams\x120\n" +
	"\x06jaeger\x18\a \x01(\v2\x18.kratos.api.JaegerConfigR\x06jaeger\x12*\n" +
	"\x04otlp\x18\b \x01(\v2\x16.kratos.api.OtlpConfigR\x04otlp\x12<\n" +
	"\n" +
	"prometheus\x18\t \x01(\v2\x1c.kratos.api.PrometheusConfigR\n" +
	"prometheus\"g\n" +
	"\rMetricsConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12<\n" +
	"\n" +
	"prometheus\x18\x02 \x01(\v2\x1c.kratos.api.PrometheusConfigR\n" +
	"prometheus\"D\n" +
	"\fJaegerConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"\\\n" +
	"\n" +
	"OtlpConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"d\n" +
	"\x10PrometheusConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\tR\binterval\"\xb3\x03\n" +
	"\x04Auth\x12/\n" +
	"\x06wpsapp\x18\x01 \x01(\v2\x17.kratos.api.Auth.WpsappR\x06wpsapp\x125\n" +
	"\bdingtalk\x18\x02 \x01(\v2\x19.kratos.api.Auth.DingtalkR\bdingtalk\x1a\xa1\x01\n" +
	"\x06Wpsapp\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x19\n" +
	"\bauth_url\x18\x03 \x01(\tR\aauthUrl\x12\x1b\n" +
	"\tauth_path\x18\x04 \x01(\tR\bauthPath\x12\x1d\n" +
	"\n" +
	"grant_type\x18\x05 \x01(\tR\tgrantType\x1a\x9e\x01\n" +
	"\bDingtalk\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x17\n" +
	"\aapp_key\x18\x02 \x01(\tR\x06appKey\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x03 \x01(\tR\tappSecret\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\tR\atimeout\x12$\n" +
	"\rmaxConcurrent\x18\x05 \x01(\x03R\rmaxConcurrentB\x1eZ\x1cnancalacc/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*App)(nil),                 // 3: kratos.api.App
	(*OpenTelemetry)(nil),       // 4: kratos.api.OpenTelemetry
	(*LogsConfig)(nil),          // 5: kratos.api.LogsConfig
	(*LokiConfig)(nil),          // 6: kratos.api.LokiConfig
	(*GormLog)(nil),             // 7: kratos.api.GormLog
	(*TracesConfig)(nil),        // 8: kratos.api.TracesConfig
	(*MetricsConfig)(nil),       // 9: kratos.api.MetricsConfig
	(*JaegerConfig)(nil),        // 10: kratos.api.JaegerConfig
	(*OtlpConfig)(nil),          // 11: kratos.api.OtlpConfig
	(*PrometheusConfig)(nil),    // 12: kratos.api.PrometheusConfig
	(*Auth)(nil),                // 13: kratos.api.Auth
	(*Server_HTTP)(nil),         // 14: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 15: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 16: kratos.api.Data.Database
	(*Data_DatabaseSync)(nil),   // 17: kratos.api.Data.DatabaseSync
	(*Data_Redis)(nil),          // 18: kratos.api.Data.Redis
	(*Data_Etcd)(nil),           // 19: kratos.api.Data.Etcd
	(*Auth_Wpsapp)(nil),         // 20: kratos.api.Auth.Wpsapp
	(*Auth_Dingtalk)(nil),       // 21: kratos.api.Auth.Dingtalk
	(*durationpb.Duration)(nil), // 22: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.app:type_name -> kratos.api.App
	13, // 3: kratos.api.Bootstrap.auth:type_name -> kratos.api.Auth
	4,  // 4: kratos.api.Bootstrap.otel:type_name -> kratos.api.OpenTelemetry
	14, // 5: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	15, // 6: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	16, // 7: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	17, // 8: kratos.api.Data.database_sync:type_name -> kratos.api.Data.DatabaseSync
	18, // 9: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	19, // 10: kratos.api.Data.etcd:type_name -> kratos.api.Data.Etcd
	8,  // 11: kratos.api.OpenTelemetry.traces:type_name -> kratos.api.TracesConfig
	9,  // 12: kratos.api.OpenTelemetry.metrics:type_name -> kratos.api.MetricsConfig
	5,  // 13: kratos.api.OpenTelemetry.logs:type_name -> kratos.api.LogsConfig
	7,  // 14: kratos.api.LogsConfig.gorm:type_name -> kratos.api.GormLog
	6,  // 15: kratos.api.LogsConfig.loki:type_name -> kratos.api.LokiConfig
	10, // 16: kratos.api.TracesConfig.jaeger:type_name -> kratos.api.JaegerConfig
	11, // 17: kratos.api.TracesConfig.otlp:type_name -> kratos.api.OtlpConfig
	12, // 18: kratos.api.TracesConfig.prometheus:type_name -> kratos.api.PrometheusConfig
	12, // 19: kratos.api.MetricsConfig.prometheus:type_name -> kratos.api.PrometheusConfig
	20, // 20: kratos.api.Auth.wpsapp:type_name -> kratos.api.Auth.Wpsapp
	21, // 21: kratos.api.Auth.dingtalk:type_name -> kratos.api.Auth.Dingtalk
	22, // 22: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	22, // 23: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	22, // 24: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	22, // 25: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
