server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s   
data:
  database:
    driver: mysql
    # 使用环境变量或加密配置
    source: ${DB_SOURCE}
    max_open_conns: 20
    max_idle_conns: 10
    conn_max_lifetime: 6h
    tag: migrate
    enable: true
  database_sync:
    driver: mysql
    source: ${SYNC_DB_SOURCE}
    source_key: ECIS_ECISACCOUNTSYNC_DB
    max_open_conns: 20
    max_idle_conns: 10
    conn_max_lifetime: 6h
    env: "prod"
  redis:
    addr: ${REDIS_ADDR}
    password: ${REDIS_PASSWORD}
    read_timeout: 0.2s
    write_timeout: 0.2s
    enable: true
  etcd:
    endpoints:
      - ${ETCD_ENDPOINT}
    dial_timeout: "5s"
    config_prefix: "/configs/nancalacc/"
    enable_config_watch: true
    enable: true  
app:
  id: "nancalacc"
  name: "nancalacc"
  version: "v1.0.0"
  env: "prod"
  log_level: "INFO"
  logout: "stdout"
  app_package: "com.acc.async"
  app_id: ${APP_ID}
  app_secret: ${APP_SECRET}
  third_company_id: ${THIRD_COMPANY_ID}
  platform_ids: ${PLATFORM_IDS}
  company_id: ${COMPANY_ID}
  access_key: ${ACCESS_KEY}
  secret_key: ${SECRET_KEY
auth:
  wpsapp:
    client_id: ${WPS_CLIENT_ID}
    client_secret: ${WPS_CLIENT_SECRET}
    auth_url: ${WPS_AUTH_URL}
    auth_path: "/openapi/oauth2/token"
    grant_type: "client_credentials"
  dingtalk:
    endpoint: "https://oapi.dingtalk.com"
    app_key: ${DINGTALK_APP_KEY}
    app_secret: ${DINGTALK_APP_SECRET}
    timeout: "5s"
    maxConcurrent: 20