server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s   
data:
  database:
    driver: mysql
    # 使用环境变量或加密配置
    source: ${DB_SOURCE}
    max_open_conns: 20
    max_idle_conns: 10
    conn_max_lifetime: 6h
    tag: migrate
    enable: false
  database_sync:
    driver: mysql
    source: root:liujianfeng@tcp(192.168.1.142:3306)/nancalacc?timeout=15s&charset=utf8mb4&parseTime=True
    source_key: ECIS_ECISACCOUNTSYNC_DB
    max_open_conns: 20
    max_idle_conns: 10
    conn_max_lifetime: 6h
    env: "dev"
    enable: true
  redis:
    addr: 192.168.1.142:6379
    password: liujianfeng
    read_timeout: 0.2s
    write_timeout: 0.2s
    enable: false
  etcd:
    endpoints:
      - ${ETCD_ENDPOINT}
    dial_timeout: "5s"
    config_prefix: "/configs/nancalacc/"
    enable_config_watch: true
    enable: false  
app:
  id: "nancalacc"
  name: "nancalacc"
  version: "v1.0.0"
  env: "prod"
  log_level: "INFO"
  logout: "stdout"
  app_package: "com.acc.async"
  app_id: "com.acc.async"
  app_secret: "dSv5TAv7fDArmoI9GQY0dxImQcb85SiO"
  third_company_id: "1" # 三方租户ID nancal
  platform_ids: "1" # 客户源数据ID dingtalkofnancal
  company_id: "1" # 云文档租户公司ID nancal
  access_key: ${ACCESS_KEY}
  secret_key: ${SECRET_KEY
auth:
  wpsapp:
    client_id: "com.acc.async"
    client_secret: "dSv5TAv7fDArmoI9GQY0dxImQcb85SiO"
    auth_url: "http://119.3.173.229"
    auth_path: "/openapi/oauth2/token"
    grant_type: "client_credentials"
  dingtalk:
   endpoint: "https://oapi.dingtalk.com"
   app_key: "dinglz1setxqhrpp7aa0"       
   app_secret: "uHVTlmVFojonyjlBIDbzsxLZ_iJfviqUMpT1LKNxP9P4TYr8LhaiwymiQfb0fjxr"
   timeout: "5s"
   maxConcurrent: 10