server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s   
data:
  database:
    driver: mysql
    source: root:|$tN_Rw!-"Eu<[50@tcp(127.0.0.1:3306)/nancalacc?timeout=15s&charset=utf8mb4&parseTime=True
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
app:
  id: "nancalacc"
  name: "nancalacc"
  version: "v1.0.0"
  env: "prov" #dev #prov
  log_level: "debug"
service:
  business:
    third_company_id: "1" # 三方租户ID
    platform_ids: "1" # 客户源数据ID
    company_id: "1" # 云文档租户公司ID
    ecisaccountsync_url: "http://encs-pri-proxy-gateway/ecisaccountsync/api/sync/all"
    ecisaccountsync_url_increment: "http://encs-pri-proxy-gateway/ecisaccountsync/api/sync/increment"  
  auth:
    self:
      app_id: "com.acc.async"
      app_name: "nancalacc"
      app_package: "com.acc.async" # 应用包名和app_secret在应用里是一对
      app_secret: "dSv5TAv7fDArmoI9GQY0dxImQcb85SiO"

      access_key: "NRSXWTPKNAIRUBMP" #有待确认
      secret_key: "SKnwwvvngrhcrpgc" #有待确认
    app:
      client_id: "com.acc.async"
      client_secret: "dSv5TAv7fDArmoI9GQY0dxImQcb85SiO"
      auth_url: "http://119.3.173.229"
      auth_path: "/openapi/oauth2/token"
      grant_type: "client_credentials"
    third:
      client_id: "your_client_id"
      client_secret: "your_secret"
      auth_url: "https://api.example.com"
      auth_path: "/openapi/oauth2/token"
      grant_type: "client_credentials"
      company_id: "1"
    user:
      client_id: "your_client_id"
      client_secret: "your_secret"
      auth_url: "https://api.example.com"
      auth_path: "/openapi/oauth2/token"
      grant_type: "authorization_code"
      redirect_uri: "https://your-app.com/callback"
    dingtalk:
      endpoint: "https://oapi.dingtalk.com"
      app_key: "dinglz1setxqhrpp7aa0"       
      app_secret: "uHVTlmVFojonyjlBIDbzsxLZ_iJfviqUMpT1LKNxP9P4TYr8LhaiwymiQfb0fjxr"
      timeout: "5s"
      maxConcurrent: 10