otel:
  enabled: true
  service:
    name: "nancalacc-test"
    version: "1.0.0"
    namespace: "nancalacc"
    instance_id: "test-instance"
  
  traces:
    enabled: true
    jaeger:
      enabled: true
      endpoint: "http://192.168.1.142:14268/api/traces"
      username: ""
      password: ""
    otlp:
      enabled: true
      endpoint: "http://192.168.1.142:4317"
      insecure: true
      timeout: "30s"
  
  logs:
    enabled: true
    level: "info"
    format: "json"
    output: "stdout"
  
  metrics:
    enabled: true
    prometheus:
      enabled: true
      endpoint: "/metrics"
      port: 9090 