server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s   
data:
  database:
    driver: mysql
    source: root:|$tN_Rw!-"Eu<[50@tcp(127.0.0.1:3306)/nancalacc?timeout=15s&charset=utf8mb4
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  dingtalk:
    endpoint: "https://oapi.dingtalk.com"
    app_key: "dinglz1setxqhrpp7aa0"       
    app_secret: "uHVTlmVFojonyjlBIDbzsxLZ_iJfviqUMpT1LKNxP9P4TYr8LhaiwymiQfb0fjxr" # 明文存储（不推荐生产环境）
    timeout: "5s"
  service_conf:
    env: "prod"
    log_level: "debug"
    access_key: "NRSXWTPKNAIRUBMP"
    secret_key: "SKnwwvvngrhcrpgc"    