server:
  http:
    addr: 0.0.0.0:8800
    timeout: 5s
  grpc:
    addr: 0.0.0.0:8900
    timeout: 5s   
data:
  database:
    driver: mysql
    source: root:|$tN_Rw!-"Eu<[50@tcp(127.0.0.1:3306)/nancalacc?timeout=15s&charset=utf8mb4&parseTime=True
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  dingtalk:
    endpoint: "https://oapi.dingtalk.com"
    app_key: "dinglz1setxqhrpp7aa0"       
    app_secret: "uHVTlmVFojonyjlBIDbzsxLZ_iJfviqUMpT1LKNxP9P4TYr8LhaiwymiQfb0fjxr"
    timeout: "5s"
  service_conf:
    env: "prov"
    log_level: "debug"
    access_key: "NRSXWTPKNAIRUBMP" #有待确认
    secret_key: "SKnwwvvngrhcrpgc" #有待确认
    app_package: "com.acc.async" # 应用包名和app_secret在应用里是一对
    app_secret: "dSv5TAv7fDArmoI9GQY0dxImQcb85SiO"
    third_company_id: "nancal" # 三方租户ID
    platform_ids: "dingtalk" # 客户源数据ID
    company_id: "nancal" # 文档平台公司ID
    ecisaccountsync_url: "http://encs-pri-open-gateway/v7/ecisaccountsync/full/sync"
